#
#
# Optimization methods for the recovery of XOR-based erasure codes
#
# Author: lyfdamon
# Since: 2017/12/29
#
#

SUBDIRS = $(CURDIR)/climb_search $(CURDIR)/sa_search $(CURDIR)/enumeration_search

all:subdirs

clean:cleansubdirs
	rm -f $(OBJECTS)

include $(MAKEINCLUDE)
