#
#
# Optimization methods for the recovery of XOR-based erasure codes
#
# Author: lyfdamon
# Since: 2017/12/28
#
#

SUBDIRS = $(CURDIR)/climb_search $(CURDIR)/sa_search $(CURDIR)/enumeration_search $(CURDIR)/ga_search

all:subdirs

clean:cleansubdirs

include $(MAKEINCLUDE)
